chore: add eslint to husky pre-commit hook
Greenstand/treetracker-wallet-app pull request #202
Opened 2021-12-15 13:28 UTC by jwgatt

fixes [#199](https://github.com/Greenstand/treetracker-wallet-web/issues/199)

2021-12-15 16:16 UTC, VWRoli requested changes
Install lint-staged first as a dev dependency otherwise, it's not going to work.

EDIT: It actually works. Installed itself but can't see it in package.json. Interesting. Why can't we see it in the package.json? @jwgatt?

You can also create a `lintstagedrc` file in the root for the settings instead of the package.json. Refer to https://github.com/Greenstand/treetracker-web-map-client/blob/web-map-site/.lintstagedrc.js

Also add `.eslintcache` to the .gitignore file.

2021-12-15 18:42 UTC, jwgatt commented
I modified the `husky.sh` executable a little so that dependencies are run with the pre-commit hook.
Will add the `.eslintcache` to the .gitignore, thanks.

2021-12-16 14:27 UTC, VWRoli commented
Alright, good job!

2021-12-16 14:28 UTC, VWRoli approved these changes

2024-07-14 20:48 UTC, closed without merging